"""The desk shell: one masthead, one grid, one stylesheet, one script.

Every HTML report composes these pure builders. The shell owns everything that
must feel identical across pages — chrome, typography, cards, badges, tabs,
anchor nav, theme flip — so a report module only writes panel content.

Theme: dark ("terminal") is the default applied theme; the choice persists in
localStorage under ONE key ('desk-theme') so it follows the reader across
every desk page. Charts re-ink via CSS custom properties, no re-render.
"""
import html as _html

from src.desk_kit import theme


def esc(v) -> str:
    return _html.escape("" if v is None else str(v), quote=True)


def num(v, fmt="{:,.2f}", dash="—"):
    try:
        f = float(v)
        if f != f:
            return dash
        return fmt.format(f)
    except (TypeError, ValueError):
        return dash


# ── Components ───────────────────────────────────────────────────────────────

def card(title, body, span=6, extra_cls="", anchor=None):
    aid = ' id="{}"'.format(esc(anchor)) if anchor else ""
    return ('<section class="card c{s}{x}"{a}><h5>{t}</h5>{b}</section>'
            .format(s=span, x=(" " + extra_cls if extra_cls else ""), a=aid,
                    t=esc(title), b=body))


_TONES = {"good": " g", "bad": " b", "warn": " w", "": ""}


def kpi(label, value, sub="", tone="", span=3):
    """Stat tile. The value is proportional-figure (display size), not
    tabular — tabular digits read loose at 24px."""
    return ('<div class="card kpi c{sp}"><div class="eye">{l}</div>'
            '<div class="kv{t}">{v}</div><div class="ks">{s}</div></div>'
            .format(sp=span, l=esc(label), t=_TONES.get(tone, ""), v=value,
                    s=sub))


def strip(cells):
    """Dense KPI strip: cells = [(label, value_html, tone)]."""
    inner = "".join(
        '<div><div class="eye">{l}</div><div class="sv{t}">{v}</div></div>'
        .format(l=esc(l), t=_TONES.get(tone, ""), v=v)
        for l, v, tone in cells)
    return ('<div class="strip" style="grid-template-columns:repeat({n},'
            'minmax(0,1fr))">{c}</div>').format(n=max(1, len(cells)), c=inner)


def badge(text, kind="warn"):
    return '<span class="badge k-{k}">{t}</span>'.format(k=esc(kind),
                                                         t=esc(text))


def verdict_pill(decision, cls_map=None):
    cls_map = cls_map or {}
    cls = cls_map.get(str(decision).upper(), "v-neutral")
    return '<span class="verdict {c}">{d}</span>'.format(c=cls,
                                                         d=esc(decision))


def rows_table(pairs):
    """Two-column label/value table; values right-aligned mono."""
    return "<table>" + "".join(
        '<tr><td>{}</td><td class="n">{}</td></tr>'.format(esc(k), v)
        for k, v in pairs) + "</table>"


def ph(text):
    return '<div class="ph">{}</div>'.format(text)


def grid(cells):
    return '<div class="grid">' + "".join(cells) + "</div>"


# ── Masthead / nav ───────────────────────────────────────────────────────────

# Relative cross-links per output directory. Every desk page links its
# siblings; the hub is regenerated by every writer so it never dangles.
DESK_LINKS = {
    "tearsheets": (("DESK", "../index.html"),
                   ("MORNING", "../briefings/latest.html"),
                   ("RESEARCH", "../research/latest.html")),
    "research": (("DESK", "../index.html"),
                 ("MORNING", "../briefings/latest.html"),
                 ("TEARSHEETS", "../tearsheets/")),
    "briefings": (("DESK", "../index.html"),
                  ("RESEARCH", "../research/latest.html"),
                  ("TEARSHEETS", "../tearsheets/")),
    "hub": (("MORNING", "briefings/latest.html"),
            ("RESEARCH", "research/latest.html"),
            ("TEARSHEETS", "tearsheets/")),
}


def tabbar(tabs):
    """tabs = [(tab_id, label)] → one shell tab group (shortcut keys 1-9)."""
    return '<nav class="tabbar" data-tabgroup>' + "".join(
        '<button class="tabbtn" data-tab="{t}">{n}&nbsp;{l}</button>'.format(
            t=esc(tid), n=i + 1, l=label)
        for i, (tid, label) in enumerate(tabs)) + "</nav>"


def anchor_nav(anchors):
    """anchors = [(section_id, label)] → sticky in-page nav with scrollspy."""
    return '<nav class="tabbar" data-spynav>' + "".join(
        '<a class="tabbtn" data-spy="{a}" href="#{a}">{l}</a>'.format(
            a=esc(aid), l=esc(label))
        for aid, label in anchors) + "</nav>"


def masthead(doc_kind, title_html, meta_html="", nav_html="", where=None):
    """The shared chrome. `where` picks the cross-link set (output dir name)."""
    links = DESK_LINKS.get(where or "", ())
    linkbar = "".join('<a class="desklink" href="{h}">{l}</a>'.format(
        h=esc(h), l=esc(l)) for l, h in links)
    return (
        '<header class="mast"><div class="mastrow">'
        '<div class="mastid"><span class="wordmark">OPTIONS DESK</span>'
        '<span class="dockind">{k}</span>{t}</div>'
        '<div class="mastmeta">{links}{meta}'
        '<button class="toggle" onclick="flipTheme()">'
        '<span id="tglabel">◑ Light</span></button></div></div>'
        "{nav}</header>"
    ).format(k=esc(doc_kind), t=title_html, links=linkbar, meta=meta_html,
             nav=nav_html)


def chipline(items):
    """Masthead meta items: [(label, value_html)] → eye-label chips."""
    return "".join('<span class="eye m">{l} {v}</span>'.format(
        l=esc(l), v=v) for l, v in items)


# ── Page assembly ────────────────────────────────────────────────────────────

def page(title, mast_html, body_html, extra_css="", extra_js=""):
    return (
        '<!DOCTYPE html>\n<html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1">'
        "<title>{title}</title><style>{tokens}{css}{extra}</style></head>"
        '<body>{mast}<main class="desk">{body}</main>'
        '<div class="tip" id="tip"></div>'
        "<script>{js}{xjs}</script></body></html>"
    ).format(title=esc(title), tokens=theme.css_tokens(), css=_CSS,
             extra=extra_css, mast=mast_html, body=body_html, js=_JS,
             xjs=extra_js)


_CSS = """
*, *::before, *::after { box-sizing:border-box; }
html { scroll-behavior:smooth; scroll-padding-top:96px; }
body { margin:0; background:var(--paper); color:var(--ink);
  font:13px/1.45 ui-sans-serif,system-ui,-apple-system,sans-serif;
  transition:background .18s ease,color .18s ease; }
.desk { max-width:1560px; margin:0 auto; padding:14px 22px 40px; }
.m,.n { font-family:ui-monospace,"SF Mono",Menlo,monospace;
  font-variant-numeric:tabular-nums; }
.eye { font-family:ui-sans-serif,system-ui,sans-serif; font-size:8.5px;
  letter-spacing:.2em; text-transform:uppercase; color:var(--muted); }
h5 { font-family:ui-sans-serif,system-ui,sans-serif; font-size:9px;
  letter-spacing:.18em; text-transform:uppercase; margin:0 0 8px;
  font-weight:700; color:var(--muted); }
.g{color:var(--good)} .b{color:var(--bad)} .w{color:var(--warn)}
.mut{color:var(--muted)}
b,strong{color:var(--ink-strong);}

/* ── masthead ── */
.mast { position:sticky; top:0; z-index:20; background:var(--paper);
  border-bottom:1px solid var(--rule-hard); padding:10px 22px 0; }
.mastrow { display:flex; justify-content:space-between; align-items:center;
  gap:12px; max-width:1560px; margin:0 auto; flex-wrap:wrap; }
.mastid { display:flex; align-items:center; gap:12px; min-width:0; }
.wordmark { font-family:ui-sans-serif,system-ui,sans-serif; font-weight:800;
  letter-spacing:.3em; font-size:12px; color:var(--ink-strong);
  white-space:nowrap; }
.dockind { font-family:ui-monospace,Menlo,monospace; font-size:10px;
  letter-spacing:.14em; border:1px solid var(--accent); color:var(--accent);
  border-radius:3px; padding:2px 7px; white-space:nowrap; }
.chip { font-family:ui-monospace,Menlo,monospace; font-size:12px;
  border:1px solid var(--rule-hard); color:var(--ink-strong);
  border-radius:3px; padding:2px 8px; letter-spacing:.08em; }
.mastmeta { display:flex; gap:12px; align-items:center; flex-wrap:wrap; }
.desklink { font-family:ui-sans-serif,system-ui,sans-serif; font-size:9px;
  letter-spacing:.16em; color:var(--muted); text-decoration:none;
  border-bottom:1px solid transparent; padding:2px 0; }
.desklink:hover { color:var(--accent); border-color:var(--accent); }
.toggle { cursor:pointer; font-family:ui-sans-serif,system-ui,sans-serif;
  font-size:10px; letter-spacing:.1em; text-transform:uppercase;
  color:var(--muted); border:1px solid var(--rule); padding:4px 9px;
  border-radius:20px; background:transparent; }
.tabbar { display:flex; gap:2px; max-width:1560px; margin:8px auto 0;
  overflow-x:auto; }
.tabbtn { cursor:pointer; font-family:ui-sans-serif,system-ui,sans-serif;
  font-size:10px; letter-spacing:.14em; text-transform:uppercase;
  font-weight:600; color:var(--muted); background:transparent;
  padding:8px 14px; border:1px solid transparent; border-bottom:none;
  border-radius:4px 4px 0 0; text-decoration:none; white-space:nowrap; }
.tabbtn:hover { color:var(--ink); }
.tabbtn.on { color:var(--ink-strong); border-color:var(--rule);
  background:var(--panel); }

/* ── grid & cards ── */
.grid { display:grid; grid-template-columns:repeat(12,minmax(0,1fr));
  gap:12px; margin-top:12px; }
.c2{grid-column:span 2} .c3{grid-column:span 3} .c4{grid-column:span 4}
.c5{grid-column:span 5} .c6{grid-column:span 6} .c7{grid-column:span 7}
.c8{grid-column:span 8} .c9{grid-column:span 9} .c12{grid-column:span 12}
@media (max-width:1100px){ .c2,.c3,.c4{grid-column:span 6}
  .c5,.c6,.c7,.c8,.c9{grid-column:span 12} }
@media (max-width:760px){ .c2,.c3,.c4,.c5,.c6,.c7,.c8,.c9{grid-column:span 12} }
.card { background:var(--panel); border:1px solid var(--rule);
  border-radius:5px; padding:12px 14px; min-width:0; }
.kpi .kv { font-size:23px; font-weight:650; margin-top:5px;
  color:var(--ink-strong); font-family:ui-sans-serif,system-ui,sans-serif; }
.kpi .kv.g{color:var(--good)} .kpi .kv.b{color:var(--bad)}
.kpi .kv.w{color:var(--warn)}
.kpi .ks { font-size:11px; color:var(--muted); margin-top:2px; }
.chead { display:flex; gap:12px; align-items:baseline; margin-bottom:6px; }
.big { font-size:19px; color:var(--ink-strong); }

/* ── tables & rows ── */
table { width:100%; border-collapse:collapse; font-size:12px; }
th { text-align:right; font-family:ui-sans-serif,system-ui,sans-serif;
  font-size:8.5px; letter-spacing:.14em; text-transform:uppercase;
  color:var(--muted); font-weight:600; padding-bottom:5px; }
th:first-child { text-align:left; }
td { padding:3px 0 3px 8px; border-top:1px solid var(--grid); }
td:first-child { padding-left:0; }
td.n { text-align:right; }
.evt { font-size:12.5px; padding:4px 0; border-top:1px solid var(--grid); }
.evt:first-child { border-top:none; }
.evt .m { color:var(--accent); margin-right:8px; }
.evt .m.g { color:var(--good); } .evt .m.b { color:var(--bad); }
.evt .m.mut { color:var(--muted); }
.evt a { color:var(--ink-strong); text-decoration:none;
  border-bottom:1px solid var(--rule-hard); }
.evt a:hover { color:var(--accent); border-color:var(--accent); }

/* ── verdicts, badges, strips ── */
.verdict { display:inline-block; font-family:ui-sans-serif,system-ui,sans-serif;
  font-weight:700; letter-spacing:.16em; text-transform:uppercase;
  font-size:12px; color:var(--paper); padding:5px 12px; border-radius:3px; }
.v-take,.v-buy{background:var(--good)} .v-skip,.v-avoid{background:var(--bad)}
.v-marg,.v-wait{background:var(--warn)} .v-ind,.v-neutral{background:var(--muted)}
.badge { display:inline-block; font-family:ui-sans-serif,system-ui,sans-serif;
  font-size:8px; padding:1px 6px; border-radius:8px; border:1px solid; }
.k-bad{border-color:var(--chip-bad-bd);color:var(--bad);background:var(--chip-bad-bg)}
.k-ok{border-color:var(--chip-ok-bd);color:var(--good);background:var(--chip-ok-bg)}
.k-warn{border-color:var(--chip-wn-bd);color:var(--warn);background:var(--chip-wn-bg)}
.strip { display:grid; border-top:1px solid var(--rule-hard);
  border-bottom:1px solid var(--rule); margin-top:10px; }
.strip>div { padding:8px 10px; border-right:1px solid var(--rule); }
.strip>div:last-child{border-right:none}
@media (max-width:900px){ .strip{grid-template-columns:repeat(3,minmax(0,1fr)) !important} }
.sv { font-family:ui-monospace,Menlo,monospace; font-variant-numeric:tabular-nums;
  font-size:15px; margin-top:3px; color:var(--ink-strong); }
.sv.g{color:var(--good)} .sv.b{color:var(--bad)} .sv.w{color:var(--warn)}

/* ── prose & callouts ── */
.lede { font-size:13.5px; line-height:1.5; margin:8px 0; max-width:72ch; }
.flipbox { margin:10px 0; font-size:12.5px; line-height:1.55;
  border-left:3px solid var(--accent); background:var(--paper);
  padding:8px 12px; border-radius:0 3px 3px 0; }
.stale { margin:12px 0 0; border-left:3px solid var(--warn);
  background:var(--chip-wn-bg); border-radius:0 3px 3px 0; padding:9px 13px;
  font-size:12.5px; }
.ph { border:1px dashed var(--rule); border-radius:3px; padding:8px 10px;
  color:var(--muted); font-family:ui-sans-serif,system-ui,sans-serif;
  font-size:11px; }
.foot { font-family:ui-monospace,Menlo,monospace; font-size:9.5px;
  color:var(--muted); margin-top:22px; border-top:1px solid var(--rule);
  padding-top:8px; line-height:1.7; }

/* ── heat grid, meter, waterfall text ── */
.heat { display:grid; gap:2px; font-size:10px; margin-top:4px; }
.heat div { padding:4px 2px; text-align:center;
  font-family:ui-monospace,Menlo,monospace; border-radius:2px;
  background:var(--hl); color:var(--ink); }
[data-theme="dark"] .heat div { background:var(--hd); }
.heat .rh { text-align:left; color:var(--muted); background:none !important; }
.meter { background:var(--grid); border:1px solid var(--rule);
  border-radius:4px; height:10px; overflow:hidden; }
.meter-fill { height:100%; border-radius:3px; }

/* ── signal bars ── */
.sig { padding:7px 0; border-top:1px solid var(--grid); }
.sig:first-child{border-top:none}
.sighead { display:flex; justify-content:space-between; font-size:11px; }
.sigbar { height:6px; background:var(--grid); border-radius:3px; margin:4px 0;
  overflow:hidden; }
.sigbar span { display:block; height:100%; border-radius:3px; }
.sigdet { font-size:11px; color:var(--muted); }

/* ── details / raw ── */
details { border:1px solid var(--rule); border-radius:5px;
  padding:8px 14px; background:var(--panel); }
details summary { cursor:pointer; font-weight:600; color:var(--ink-strong);
  font-size:12.5px; }
details[open] summary { margin-bottom:8px; }
.raw { font-family:ui-monospace,Menlo,monospace; font-size:10px;
  line-height:1.45; background:var(--paper); border:1px solid var(--rule);
  border-radius:4px; padding:10px; max-height:420px; overflow:auto;
  white-space:pre-wrap; word-break:break-word; }

/* ── tooltip, panes, print ── */
.tip { position:fixed; display:none; z-index:50; pointer-events:none;
  background:var(--panel); border:1px solid var(--rule-hard);
  color:var(--ink-strong); font-family:ui-monospace,Menlo,monospace;
  font-size:11px; padding:5px 9px; border-radius:4px;
  box-shadow:0 4px 14px rgba(0,0,0,.25); }
.pane { animation:fadein .12s ease; }
@keyframes fadein { from{opacity:.4} to{opacity:1} }
@media print {
  .mast{position:static} .tabbar,.toggle,.desklink{display:none}
  .pane{display:block !important; page-break-inside:avoid;
    margin-bottom:18px}
  .raw{max-height:none}
}
"""

_JS = """
(function () {
  var root = document.documentElement;
  function applyTheme(t) {
    root.setAttribute('data-theme', t);
    var el = document.getElementById('tglabel');
    if (el) el.textContent = t === 'dark' ? '\\u25d1 Light' : '\\u25d0 Dark';
  }
  var saved = null;
  try { saved = localStorage.getItem('desk-theme'); } catch (e) {}
  applyTheme(saved || 'dark');
  window.flipTheme = function () {
    var next = root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
    applyTheme(next);
    try { localStorage.setItem('desk-theme', next); } catch (e) {}
  };

  // Tab groups: any [data-tabgroup] nav drives sibling .pane elements whose
  // ids are 'pane-' + data-tab. The first group also owns the 1-9 keys and
  // the location hash.
  var groups = Array.prototype.slice.call(
    document.querySelectorAll('[data-tabgroup]'));
  groups.forEach(function (nav, gi) {
    var tabs = Array.prototype.slice.call(nav.querySelectorAll('[data-tab]'));
    if (!tabs.length) return;
    var scope = nav.getAttribute('data-scope');
    var panes = Array.prototype.slice.call(
      (scope ? document.getElementById(scope) : document)
        .querySelectorAll('.pane'));
    function show(id) {
      tabs.forEach(function (b) {
        b.classList.toggle('on', b.dataset.tab === id); });
      panes.forEach(function (p) {
        p.style.display = (p.id === 'pane-' + id) ? '' : 'none';
      });
      if (gi === 0 && history.replaceState)
        history.replaceState(null, '', '#' + id);
    }
    tabs.forEach(function (b) {
      b.addEventListener('click', function () { show(b.dataset.tab); });
    });
    if (gi === 0) {
      document.addEventListener('keydown', function (e) {
        if (e.metaKey || e.ctrlKey || e.altKey) return;
        var tag = (document.activeElement && document.activeElement.tagName) || '';
        if (tag === 'INPUT' || tag === 'TEXTAREA') return;
        var i = parseInt(e.key, 10);
        if (i >= 1 && i <= tabs.length) show(tabs[i - 1].dataset.tab);
      });
      var want = (location.hash || '').slice(1);
      var ok = tabs.some(function (b) { return b.dataset.tab === want; });
      show(ok ? want : tabs[0].dataset.tab);
    } else {
      show(tabs[0].dataset.tab);
    }
  });

  // Scrollspy for anchor navs: highlight the section currently in view.
  var spynav = document.querySelector('[data-spynav]');
  if (spynav && 'IntersectionObserver' in window) {
    var links = Array.prototype.slice.call(
      spynav.querySelectorAll('[data-spy]'));
    var byId = {};
    links.forEach(function (a) { byId[a.dataset.spy] = a; });
    var current = null;
    var obs = new IntersectionObserver(function (entries) {
      entries.forEach(function (en) {
        if (en.isIntersecting) current = en.target.id;
      });
      if (current && byId[current]) {
        links.forEach(function (a) {
          a.classList.toggle('on', a.dataset.spy === current); });
      }
    }, { rootMargin: '-45% 0px -50% 0px' });
    links.forEach(function (a) {
      var sec = document.getElementById(a.dataset.spy);
      if (sec) obs.observe(sec);
    });
  }

  // Crosshair tooltips on charts carrying class="xh".
  var tip = document.getElementById('tip');
  Array.prototype.forEach.call(document.querySelectorAll('svg.xh'),
      function (svg) {
    var labels, ys;
    try {
      labels = JSON.parse(svg.dataset.labels || '[]');
      ys = JSON.parse(svg.dataset.ys || '[]');
    } catch (e) { return; }
    if (!labels.length) return;
    var x0 = parseFloat(svg.dataset.x0), step = parseFloat(svg.dataset.step);
    var line = svg.querySelector('.ch-line'), dot = svg.querySelector('.ch-dot');
    var vb = (svg.getAttribute('viewBox') || '0 0 760 200').split(/\\s+/);
    var vw = parseFloat(vb[2]);
    svg.addEventListener('mousemove', function (e) {
      var r = svg.getBoundingClientRect();
      var sx = (e.clientX - r.left) * (vw / r.width);
      var i = Math.round((sx - x0) / step);
      if (i < 0) i = 0;
      if (i >= labels.length) i = labels.length - 1;
      var cx = x0 + i * step;
      if (line) { line.setAttribute('x1', cx); line.setAttribute('x2', cx);
                  line.setAttribute('visibility', 'visible'); }
      if (dot && ys[i] != null) { dot.setAttribute('cx', cx);
        dot.setAttribute('cy', ys[i]); dot.setAttribute('visibility', 'visible'); }
      if (tip) {
        tip.textContent = labels[i];
        tip.style.display = 'block';
        var tx = e.clientX + 14, ty = e.clientY - 12;
        if (tx + tip.offsetWidth > window.innerWidth - 8)
          tx = e.clientX - tip.offsetWidth - 14;
        tip.style.left = tx + 'px'; tip.style.top = ty + 'px';
      }
    });
    svg.addEventListener('mouseleave', function () {
      if (line) line.setAttribute('visibility', 'hidden');
      if (dot) dot.setAttribute('visibility', 'hidden');
      if (tip) tip.style.display = 'none';
    });
  });
})();
"""
